name: Generate Metrics

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: java
          plugin_languages_limit: 8
          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          config_timezone: America/Sao_Paulo
          config_display: large
          config_order: base.header, base.repositories, languages, achievements, habits
